ansible_ssh_common_args: ''

es_api_scheme: "https"
es_api_port: 9200
es_api_uri: "{{ es_api_scheme }}://{{ es_api_host }}:{{ es_api_port }}"

es_security_api: '_security'
es_api_basic_auth_username: 'admin'
es_api_basic_auth_password: "{{ es_api_basic_auth_password }}"

es_validate_certs: no

es_roles:
  native:
    jaeger_admin:
      cluster: []
      indices:
      - names: 'jaeger-*'
        privileges:
        - create_index
        - write
    fluentd_admin:
      cluster: []
      indices:
      - names: 'logstash-*'
        privileges:
        - create
        - delete
        - index
        - manage
        - read
    fluentd_monitor_admin:
      cluster: ['monitor']


es_users:
  native:
    jaeger_admin:
      password: "{{ jaeger_admin_password }}"
      roles:
      - jaeger_admin_role
    fluentd_admin:
      password: "{{ fluentd_admin_password }}"
      roles:
      - fluentd_admin
      - fluentd_monitor_admin
